# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://https://github.com/BenUlcoq/texas_hold_em_simulator" }

# gem "rails"

gem 'colorize', '~> 0.8.1'

gem 'artii', '~> 2.1'

gem 'ruby-poker', '~> 1.0'

gem 'test-unit', '~> 3.3'

gem 'random_data', '~> 1.6'

gem "launchy", "~> 2.4"
